CREATE TABLE `competitor_intelligence` (
	`id` int AUTO_INCREMENT NOT NULL,
	`competitorName` varchar(255) NOT NULL,
	`competitorUrl` varchar(500),
	`intelligenceType` enum('website_change','new_program','pricing_change','social_campaign','ranking_change','partnership_announcement','event','promotion','general') NOT NULL,
	`title` varchar(500) NOT NULL,
	`summary` text,
	`details` text,
	`sourceUrl` text,
	`severity` enum('low','medium','high','critical') DEFAULT 'medium',
	`strategicRecommendation` text,
	`actionRequired` boolean DEFAULT false,
	`actionTaken` boolean DEFAULT false,
	`status` enum('new','reviewed','actioned','dismissed') DEFAULT 'new',
	`reviewedAt` timestamp,
	`reviewedBy` varchar(255),
	`detectedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `competitor_intelligence_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `competitor_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`websiteUrl` varchar(500),
	`instagramUrl` varchar(500),
	`facebookUrl` varchar(500),
	`tiktokUrl` varchar(500),
	`linkedinUrl` varchar(500),
	`description` text,
	`services` text,
	`countries` text,
	`estimatedStudents` varchar(100),
	`strengths` text,
	`weaknesses` text,
	`lastScannedAt` timestamp,
	`lastSnapshotHash` varchar(64),
	`isActive` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `competitor_profiles_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `social_mentions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`platform` enum('instagram','facebook','tiktok','twitter','linkedin','youtube','other') NOT NULL,
	`mentionType` enum('lead_signal','competitor_activity','brand_mention','industry_trend') NOT NULL,
	`authorName` varchar(255),
	`authorHandle` varchar(255),
	`content` text,
	`sourceUrl` text,
	`sentiment` enum('positive','negative','neutral'),
	`relevanceScore` int DEFAULT 0,
	`isLeadOpportunity` boolean DEFAULT false,
	`convertedToLead` boolean DEFAULT false,
	`leadId` int,
	`status` enum('new','reviewed','actioned','dismissed') DEFAULT 'new',
	`detectedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `social_mentions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `university_partnerships` (
	`id` int AUTO_INCREMENT NOT NULL,
	`universityName` varchar(500) NOT NULL,
	`country` varchar(100) NOT NULL,
	`city` varchar(255),
	`websiteUrl` varchar(500),
	`worldRanking` int,
	`countryRanking` int,
	`rankingSource` varchar(100),
	`partnershipType` enum('agent_agreement','pathway_program','scholarship_partner','articulation_agreement','exchange_program','general') DEFAULT 'agent_agreement',
	`hasExistingIndonesianAgent` boolean,
	`existingAgents` text,
	`internationalOfficeEmail` varchar(320),
	`agentRecruitmentEmail` varchar(320),
	`contactPersonName` varchar(255),
	`contactPersonTitle` varchar(255),
	`contactPersonLinkedin` varchar(500),
	`popularPrograms` text,
	`tuitionRange` varchar(255),
	`intakeMonths` varchar(255),
	`outreachStatus` enum('identified','researching','draft_ready','email_sent','follow_up_sent','responded','meeting_scheduled','agreement_pending','partnered','rejected','no_response') DEFAULT 'identified',
	`outreachEmailDraft` text,
	`outreachSentAt` timestamp,
	`lastFollowUpAt` timestamp,
	`responseReceived` text,
	`partnershipScore` int DEFAULT 0,
	`priority` enum('low','medium','high','critical') DEFAULT 'medium',
	`notes` text,
	`discoveredAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `university_partnerships_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `visitor_tracking` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sessionId` varchar(64) NOT NULL,
	`visitorFingerprint` varchar(128),
	`ipAddress` varchar(45),
	`userAgent` text,
	`pagesVisited` text,
	`totalPageViews` int DEFAULT 0,
	`timeOnSite` int DEFAULT 0,
	`referrerUrl` text,
	`utmSource` varchar(255),
	`utmMedium` varchar(255),
	`utmCampaign` varchar(255),
	`chatbotEngaged` boolean DEFAULT false,
	`formStarted` boolean DEFAULT false,
	`formCompleted` boolean DEFAULT false,
	`contactPageVisited` boolean DEFAULT false,
	`ieltsPageVisited` boolean DEFAULT false,
	`countryPagesVisited` text,
	`aptitudeTestStarted` boolean DEFAULT false,
	`engagementScore` int DEFAULT 0,
	`isHighIntent` boolean DEFAULT false,
	`convertedToLead` boolean DEFAULT false,
	`leadId` int,
	`firstVisitAt` timestamp NOT NULL DEFAULT (now()),
	`lastActivityAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `visitor_tracking_id` PRIMARY KEY(`id`)
);
