CREATE TABLE `seo_page_audits` (
	`id` int AUTO_INCREMENT NOT NULL,
	`pageUrl` varchar(500) NOT NULL,
	`pageTitle` varchar(500),
	`metaTitle` varchar(500),
	`metaTitleLength` int,
	`metaTitleScore` int,
	`metaDescription` text,
	`metaDescriptionLength` int,
	`metaDescriptionScore` int,
	`hasOgTitle` boolean DEFAULT false,
	`hasOgDescription` boolean DEFAULT false,
	`hasOgImage` boolean DEFAULT false,
	`h1Count` int DEFAULT 0,
	`h2Count` int DEFAULT 0,
	`imageCount` int DEFAULT 0,
	`imagesWithAlt` int DEFAULT 0,
	`wordCount` int DEFAULT 0,
	`internalLinks` int DEFAULT 0,
	`externalLinks` int DEFAULT 0,
	`hasCanonical` boolean DEFAULT false,
	`hasStructuredData` boolean DEFAULT false,
	`isIndexable` boolean DEFAULT true,
	`loadTimeMs` int,
	`overallScore` int DEFAULT 0,
	`issues` text,
	`recommendations` text,
	`targetKeyword` varchar(255),
	`keywordInTitle` boolean DEFAULT false,
	`keywordInDescription` boolean DEFAULT false,
	`keywordInH1` boolean DEFAULT false,
	`keywordDensity` varchar(10),
	`auditedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `seo_page_audits_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `seo_recommendations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`auditId` int,
	`pageUrl` varchar(500) NOT NULL,
	`type` enum('meta_title','meta_description','og_tags','h1_missing','h1_multiple','alt_text','internal_links','keyword_optimization','structured_data','canonical','content_length','load_speed','sitemap') NOT NULL,
	`severity` enum('critical','warning','info') NOT NULL DEFAULT 'warning',
	`title` varchar(255) NOT NULL,
	`description` text,
	`currentValue` text,
	`suggestedValue` text,
	`status` enum('open','applied','dismissed') NOT NULL DEFAULT 'open',
	`appliedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `seo_recommendations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `seo_score_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`overallScore` int NOT NULL DEFAULT 0,
	`metaScore` int DEFAULT 0,
	`contentScore` int DEFAULT 0,
	`technicalScore` int DEFAULT 0,
	`pagesAudited` int DEFAULT 0,
	`issuesFound` int DEFAULT 0,
	`issuesFixed` int DEFAULT 0,
	`topIssues` text,
	`reportSentAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `seo_score_history_id` PRIMARY KEY(`id`)
);
