CREATE TABLE `university_reply_queue` (
	`id` int AUTO_INCREMENT NOT NULL,
	`universityPartnershipId` int NOT NULL,
	`universityName` varchar(500) NOT NULL,
	`universityCountry` varchar(100),
	`resendEmailId` varchar(128),
	`fromEmail` varchar(320) NOT NULL,
	`fromName` varchar(255),
	`subject` varchar(500),
	`emailBody` text,
	`receivedAt` timestamp NOT NULL DEFAULT (now()),
	`classification` enum('interested','needs_more_info','declined','counter_offer','meeting_request','unknown') DEFAULT 'unknown',
	`classificationReason` text,
	`sentiment` enum('positive','neutral','negative') DEFAULT 'neutral',
	`urgency` enum('low','medium','high') DEFAULT 'medium',
	`keyPoints` text,
	`draftedResponse` text,
	`draftedSubject` varchar(500),
	`approvalStatus` enum('pending_review','approved','edited_and_approved','declined','sent','failed') DEFAULT 'pending_review',
	`approvedAt` timestamp,
	`declinedAt` timestamp,
	`declineReason` text,
	`editedResponse` text,
	`sentAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `university_reply_queue_id` PRIMARY KEY(`id`),
	CONSTRAINT `university_reply_queue_resendEmailId_unique` UNIQUE(`resendEmailId`)
);
