import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import {
  Sparkles,
  Headphones,
  BookOpen,
  FileText,
  MessageCircle,
  CheckCircle,
  Clock,
  TrendingUp,
  Award,
  Zap,
  ShieldCheck,
  ArrowRight,
} from "lucide-react";
import { SEO } from "@/components/SEO";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";

// Images generated by scripts/generate-ielts-landing-images.ts and uploaded
// to R2; served via the /files/* Express proxy.
const IMG_HERO = "/files/ielts/landing/hero.png";
const IMG_SUCCESS = "/files/ielts/landing/success-students.png";
const IMG_REPORT = "/files/ielts/landing/report-mockup.png";
const IMG_SKILL = {
  listening: "/files/ielts/landing/skill-listening.png",
  reading: "/files/ielts/landing/skill-reading.png",
  writing: "/files/ielts/landing/skill-writing.png",
  speaking: "/files/ielts/landing/skill-speaking.png",
};

const SKILLS = [
  {
    icon: Headphones,
    title: "Listening",
    detail: "4 sections, 40 questions, plays once — just like the real test.",
    img: IMG_SKILL.listening,
    color: "from-blue-500 to-indigo-600",
    bg: "bg-blue-50",
    border: "border-blue-200",
  },
  {
    icon: BookOpen,
    title: "Reading",
    detail: "3 passages, 40 questions, 60 minutes. Academic or General.",
    img: IMG_SKILL.reading,
    color: "from-emerald-500 to-teal-600",
    bg: "bg-emerald-50",
    border: "border-emerald-200",
  },
  {
    icon: FileText,
    title: "Writing",
    detail: "Task 1 + Task 2, AI-graded against the official IELTS rubric.",
    img: IMG_SKILL.writing,
    color: "from-purple-500 to-fuchsia-600",
    bg: "bg-purple-50",
    border: "border-purple-200",
  },
  {
    icon: MessageCircle,
    title: "Speaking",
    detail: "Live AI examiner agent — a real conversation, just like the exam.",
    img: IMG_SKILL.speaking,
    color: "from-rose-500 to-pink-600",
    bg: "bg-rose-50",
    border: "border-rose-200",
  },
];

const HOW_STEPS = [
  {
    icon: Zap,
    title: "1. Bayar Rp 79k",
    detail: "Checkout 1-klik via Xendit (BCA, Mandiri, GoPay, DANA, OVO, ShopeePay, kartu kredit). Akses langsung.",
  },
  {
    icon: Clock,
    title: "2. Kerjakan 4 skill",
    detail: "Listening, Reading, Writing, Speaking — sekaligus seperti tes IELTS resmi (~2 jam 45 menit).",
  },
  {
    icon: TrendingUp,
    title: "3. Terima band score",
    detail: "AI grade setiap skill dalam menit. PDF report profesional langsung ke email kamu.",
  },
];

const FAQ = [
  {
    q: "Is this the same as the official IELTS test?",
    a: "No. This is a practice mock test designed to mirror the official IELTS format, timing, and band-scoring system. It does NOT give you an official IELTS score — only practice. We're not affiliated with British Council, IDP, or Cambridge.",
  },
  {
    q: "How accurate is the AI scoring?",
    a: "Listening and Reading are auto-graded against answer keys — 100% accurate. Writing and Speaking are graded by AI against the official IELTS public band descriptors. Expect ±0.5 band accuracy compared to a human examiner.",
  },
  {
    q: "Can I take it more than once?",
    a: "Yes — each purchase = one attempt. You can buy as many attempts as you want. We rotate among multiple tests so you don't see the same questions.",
  },
  {
    q: "How long does the test take?",
    a: "About 2 hours 45 minutes total — same as the real IELTS exam. Listening (30 min), Reading (60 min), Writing (60 min), Speaking (~14 min).",
  },
  {
    q: "Do I need any special equipment?",
    a: "Headphones for Listening, and a working microphone for Speaking. Both should already be on your laptop or phone.",
  },
];

export default function IeltsMockTest() {
  const { loading: authLoading } = useAuth();
  const catalog = trpc.ielts.catalog.useQuery();
  const bundleCatalog = trpc.ielts.bundleCatalog.useQuery();
  const startCheckout = trpc.ielts.startCheckout.useMutation();
  const startBundleCheckout = trpc.ielts.startBundleCheckout.useMutation();

  const [testType, setTestType] = useState<"academic" | "general">("academic");
  const [purchaseMode, setPurchaseMode] = useState<"mock_only" | "bundle">("mock_only");
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [phone, setPhone] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [openFaq, setOpenFaq] = useState<number | null>(0);

  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  // Note: intentionally do NOT prefill name/email from the logged-in account —
  // the test taker enters their own details on the form.

  const failedFlag = new URLSearchParams(window.location.search).get("failed") === "1";

  const handleBuy = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);
    // Guest checkout — no account or login required. The buyer enters their
    // own name/email here; we email them the payment link, then (on payment)
    // the secret take-test link. The token in that link authorizes everything.
    if (!name.trim() || !email.trim()) {
      setError("Name and email are required");
      return;
    }
    try {
      // Bundle path: single Rp 299k invoice that activates Mock + Tutor 30d
      if (purchaseMode === "bundle") {
        const res = await startBundleCheckout.mutateAsync({
          testType,
          plan: "mock_tutor_m1",
          customerName: name.trim(),
          customerEmail: email.trim(),
          customerPhone: phone.trim() || undefined,
        });
        window.location.href = res.invoiceUrl;
        return;
      }

      // Standalone Mock Test (Rp 79k)
      const res = await startCheckout.mutateAsync({
        testType,
        customerName: name.trim(),
        customerEmail: email.trim(),
        customerPhone: phone.trim() || undefined,
      });
      // Free trial bypasses Xendit and gives back an attempt token directly.
      if (res.trial) {
        window.location.href = `/ielts/mock-test/take/${res.attemptToken}`;
      } else {
        window.location.href = res.invoiceUrl;
      }
    } catch (err: any) {
      setError(err?.message ?? "Could not start checkout");
    }
  };

  const idr = (n: number) =>
    new Intl.NumberFormat("id-ID", {
      style: "currency",
      currency: "IDR",
      minimumFractionDigits: 0,
    }).format(n);

  const academicCount = catalog.data?.academicTests ?? 0;
  const generalCount = catalog.data?.generalTests ?? 0;
  const academicFree = catalog.data?.academicFree ?? false;
  const generalFree = catalog.data?.generalFree ?? false;
  const isFreeNow =
    (testType === "academic" && academicFree) ||
    (testType === "general" && generalFree);
  const price = catalog.data?.priceIdr ?? 79000;
  const buyDisabled =
    authLoading ||
    startCheckout.isPending ||
    (testType === "academic" && academicCount === 0) ||
    (testType === "general" && generalCount === 0);

  return (
    <div className="min-h-screen bg-white">
      <SEO
        title="IELTS Mock Test — Full 4-Skill Practice Exam | SpecTa Education"
        description="A full-length IELTS mock test (Listening, Reading, Writing, Speaking) graded by AI. Get your band score and a detailed report — instantly, for IDR 79,000."
        keywords="IELTS mock test, IELTS prediction test, IELTS practice online, IELTS Indonesia, simulasi IELTS, mock test IELTS, latihan IELTS"
      />
      <Navigation currentPage="ielts" />

      {/* HERO */}
      <section className="pt-24 pb-20 px-4 relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-blue-600 via-indigo-600 to-purple-700" />
        <div
          className="absolute inset-0"
          style={{
            backgroundImage:
              "radial-gradient(circle at 20% 30%, rgba(255,255,255,0.18) 0%, transparent 50%), radial-gradient(circle at 80% 20%, rgba(255,255,255,0.10) 0%, transparent 40%)",
          }}
        />
        <div className="absolute top-32 left-[8%] w-24 h-24 bg-white/10 rounded-3xl rotate-12 blur-sm" />
        <div className="absolute bottom-16 right-[12%] w-40 h-40 bg-white/5 rounded-full blur-md" />
        <div className="absolute top-44 right-[28%] w-16 h-16 bg-amber-300/25 rounded-2xl -rotate-12" />

        <div className="container relative z-10">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <motion.div
              initial={{ opacity: 0, x: -30 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.6 }}
            >
              <motion.div
                className="inline-flex items-center gap-2 px-5 py-2.5 bg-amber-400 text-slate-900 rounded-full text-sm font-bold mb-6 shadow-lg"
                initial={{ opacity: 0, y: -10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.2 }}
              >
                <Sparkles className="w-4 h-4" />
                Hanya {idr(price)} · AI Grading · Report Instan
              </motion.div>
              {/* Bahasa-primary hero (target market: Indonesian students) with
                  English support subtext. Matches ad-copy promises: "Simulasi
                  IELTS", "Prediksi Skor", "Latihan Terstruktur" all resolved. */}
              <h1 className="text-4xl md:text-6xl font-bold mb-4 text-white leading-tight">
                Simulasi IELTS Lengkap
                <br />
                <span className="bg-clip-text text-transparent bg-gradient-to-r from-yellow-200 to-amber-200">
                  4 Skill · Rp 79.000
                </span>
              </h1>
              <p className="text-lg text-white/95 mb-2 max-w-lg leading-relaxed font-medium">
                Cek prediksi band IELTS kamu sebelum ambil tes resmi.
              </p>
              <p className="text-base text-white/80 mb-6 max-w-lg leading-relaxed">
                Latihan lengkap 4 skill (Listening, Reading, Writing, Speaking) — AI grading sesuai rubrik IELTS resmi. Report PDF profesional dikirim ke email dalam menit.
              </p>
              <div className="flex flex-wrap items-center gap-3 mb-6">
                <div className="flex items-center gap-2 px-4 py-2 bg-white/15 backdrop-blur-sm rounded-xl border border-white/20 text-white text-sm">
                  <CheckCircle className="w-4 h-4 text-amber-200" />
                  4 skill lengkap
                </div>
                <div className="flex items-center gap-2 px-4 py-2 bg-white/15 backdrop-blur-sm rounded-xl border border-white/20 text-white text-sm">
                  <CheckCircle className="w-4 h-4 text-amber-200" />
                  Speaking dengan AI
                </div>
                <div className="flex items-center gap-2 px-4 py-2 bg-white/15 backdrop-blur-sm rounded-xl border border-white/20 text-white text-sm">
                  <CheckCircle className="w-4 h-4 text-amber-200" />
                  PDF report
                </div>
              </div>
              {/* Big prominent CTA + inline pricing (mobile friendly).
                  Google Ads policy also requires recurring/one-off price on CTA. */}
              <a
                href="#buy"
                className="inline-flex items-center justify-center gap-2 bg-amber-400 hover:bg-amber-300 text-slate-900 font-bold text-lg px-8 py-4 rounded-xl transition shadow-xl w-full sm:w-auto"
              >
                Beli Sekarang — {idr(price)}
                <ArrowRight className="w-5 h-5" />
              </a>
              <p className="text-white/70 text-xs mt-3">
                ✓ Sekali bayar, no subscription · ✓ Hasil dalam menit · ✓ Trusted since 2005 · 10.000+ siswa
              </p>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, x: 30 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.6, delay: 0.1 }}
              className="relative"
            >
              <div className="relative rounded-3xl overflow-hidden shadow-2xl ring-1 ring-white/20">
                <img
                  src={IMG_HERO}
                  alt="A student preparing for the IELTS test"
                  className="w-full h-auto object-cover"
                  loading="eager"
                  onError={e => {
                    (e.currentTarget as HTMLImageElement).style.display = "none";
                  }}
                />
              </div>
              {/* Floating price chip — now visible on ALL screens (previously
                  hidden md:block dropped it entirely on mobile, hiding the
                  price from ~70% of Indonesian visitors). */}
              <div className="absolute -bottom-6 left-2 sm:-left-6 bg-white rounded-2xl shadow-2xl px-4 sm:px-5 py-3 sm:py-4 border-2 border-amber-400">
                <div className="text-[10px] sm:text-xs text-slate-500 uppercase tracking-wider font-semibold">
                  Bayar 1× · No Subscription
                </div>
                <div className="text-xl sm:text-2xl font-black text-slate-900">
                  {idr(price)}
                </div>
                <div className="text-[10px] sm:text-xs text-emerald-700 font-bold">
                  vs Rp 3.400.000 IELTS resmi = 97% lebih murah
                </div>
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* COMPARISON BAR */}
      <section className="py-12 px-4 bg-slate-50">
        <div className="container">
          <div className="grid md:grid-cols-3 gap-6 max-w-4xl mx-auto">
            <ComparisonCard
              label="IELTS Resmi"
              value="Rp 3.400.000"
              sub="Tunggu 13 hari · 1× per bayar"
              tone="muted"
            />
            <ComparisonCard
              label="SpecTa Mock"
              value={idr(price)}
              sub="Report instan · beli ulang kapan aja"
              tone="primary"
            />
            <ComparisonCard
              label="Kamu Hemat"
              value="~97%"
              sub="setiap kali latihan"
              tone="accent"
            />
          </div>
        </div>
      </section>

      {/* WHAT'S INCLUDED — 4 skill cards */}
      <section className="py-20 px-4">
        <div className="container">
          <div className="text-center max-w-2xl mx-auto mb-12">
            <span className="inline-block px-4 py-1.5 bg-blue-50 text-blue-700 text-xs font-semibold rounded-full mb-3">
              The complete test
            </span>
            <h2 className="text-3xl md:text-4xl font-bold text-slate-900 mb-3">
              All four skills, end to end
            </h2>
            <p className="text-slate-600">
              We replicate the format, timing, and band-scoring of the real
              IELTS Academic and General Training tests.
            </p>
          </div>
          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {SKILLS.map((s, i) => (
              <motion.div
                key={s.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.4, delay: i * 0.08 }}
                className={`rounded-3xl overflow-hidden border ${s.border} ${s.bg} hover:shadow-lg transition`}
              >
                <div className="aspect-square w-full overflow-hidden bg-slate-100">
                  <img
                    src={s.img}
                    alt={s.title}
                    className="w-full h-full object-cover"
                    loading="lazy"
                    onError={e => {
                      (e.currentTarget as HTMLImageElement).style.display = "none";
                    }}
                  />
                </div>
                <div className="p-5">
                  <div
                    className={`inline-flex items-center justify-center w-10 h-10 rounded-xl bg-gradient-to-br ${s.color} text-white mb-3 shadow`}
                  >
                    <s.icon className="w-5 h-5" />
                  </div>
                  <h3 className="font-semibold text-slate-900 mb-1">{s.title}</h3>
                  <p className="text-sm text-slate-600 leading-relaxed">
                    {s.detail}
                  </p>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* HOW IT WORKS */}
      <section className="py-20 px-4 bg-gradient-to-b from-white to-slate-50">
        <div className="container">
          <div className="text-center max-w-2xl mx-auto mb-12">
            <span className="inline-block px-4 py-1.5 bg-emerald-50 text-emerald-700 text-xs font-semibold rounded-full mb-3">
              How it works
            </span>
            <h2 className="text-3xl md:text-4xl font-bold text-slate-900 mb-3">
              From purchase to band score in one sitting
            </h2>
          </div>
          <div className="grid md:grid-cols-3 gap-6 max-w-4xl mx-auto">
            {HOW_STEPS.map((step, i) => (
              <motion.div
                key={step.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.4, delay: i * 0.1 }}
                className="bg-white rounded-2xl border border-slate-200 p-6 shadow-sm relative"
              >
                <div className="absolute -top-3 -left-3 w-9 h-9 rounded-full bg-gradient-to-br from-blue-600 to-indigo-700 text-white font-bold flex items-center justify-center text-sm shadow">
                  {i + 1}
                </div>
                <step.icon className="w-7 h-7 text-blue-600 mb-3" />
                <h3 className="font-semibold text-slate-900 mb-1">
                  {step.title}
                </h3>
                <p className="text-sm text-slate-600">{step.detail}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* SAMPLE REPORT PREVIEW */}
      <section className="py-20 px-4">
        <div className="container">
          <div className="grid lg:grid-cols-2 gap-12 items-center max-w-5xl mx-auto">
            <motion.div
              initial={{ opacity: 0, x: -20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5 }}
              className="rounded-3xl overflow-hidden shadow-xl border border-slate-200"
            >
              <img
                src={IMG_REPORT}
                alt="Sample band-score report"
                className="w-full h-auto object-cover"
                loading="lazy"
                onError={e => {
                  (e.currentTarget as HTMLImageElement).style.display = "none";
                }}
              />
            </motion.div>
            <div>
              <span className="inline-block px-4 py-1.5 bg-amber-50 text-amber-700 text-xs font-semibold rounded-full mb-3">
                You get a real report
              </span>
              <h2 className="text-3xl md:text-4xl font-bold text-slate-900 mb-4">
                A band-score report you can actually use
              </h2>
              <p className="text-slate-600 mb-6 leading-relaxed">
                Inspired by the official IELTS Test Report Form. Includes your
                overall band, sub-scores per skill, per-criterion feedback,
                and a personalised study plan based on what to improve next.
              </p>
              <ul className="space-y-3 text-sm text-slate-700">
                <li className="flex items-start gap-2">
                  <Award className="w-5 h-5 text-amber-500 mt-0.5 shrink-0" />
                  Overall band score on the standard 0–9 scale
                </li>
                <li className="flex items-start gap-2">
                  <Award className="w-5 h-5 text-amber-500 mt-0.5 shrink-0" />
                  Sub-scores per skill (FC, LR, GRA, P for Speaking; TA, CC,
                  LR, GRA for Writing)
                </li>
                <li className="flex items-start gap-2">
                  <Award className="w-5 h-5 text-amber-500 mt-0.5 shrink-0" />
                  Written feedback per criterion
                </li>
                <li className="flex items-start gap-2">
                  <Award className="w-5 h-5 text-amber-500 mt-0.5 shrink-0" />
                  Branded SpecTa PDF, emailed instantly
                </li>
              </ul>
            </div>
          </div>
        </div>
      </section>

      {/* SUCCESS / TRUST BAND */}
      <section className="py-20 px-4 bg-gradient-to-br from-blue-50 via-indigo-50 to-purple-50">
        <div className="container">
          <div className="grid lg:grid-cols-2 gap-12 items-center max-w-5xl mx-auto">
            <div>
              <span className="inline-block px-4 py-1.5 bg-white text-indigo-700 text-xs font-semibold rounded-full mb-3 shadow-sm">
                Built by IELTS experts
              </span>
              <h2 className="text-3xl md:text-4xl font-bold text-slate-900 mb-4">
                The same team that's coached 6,000+ students since 2005
              </h2>
              <p className="text-slate-600 mb-6 leading-relaxed">
                SpecTa Education has been preparing Indonesian students for
                IELTS for two decades. This mock test is the same content kit
                our top instructors use in class — now available as a
                self-service AI-graded test you can take any time.
              </p>
              <div className="flex flex-wrap gap-3">
                <Pill icon={ShieldCheck} text="20 years experience" />
                <Pill icon={TrendingUp} text="6,000+ students" />
                <Pill icon={Award} text="Real IELTS rubric" />
              </div>
            </div>
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              whileInView={{ opacity: 1, scale: 1 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5 }}
              className="rounded-3xl overflow-hidden shadow-xl"
            >
              <img
                src={IMG_SUCCESS}
                alt="Students celebrating IELTS success"
                className="w-full h-auto object-cover"
                loading="lazy"
                onError={e => {
                  (e.currentTarget as HTMLImageElement).style.display = "none";
                }}
              />
            </motion.div>
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="py-20 px-4">
        <div className="container">
          <div className="text-center max-w-2xl mx-auto mb-10">
            <span className="inline-block px-4 py-1.5 bg-slate-100 text-slate-700 text-xs font-semibold rounded-full mb-3">
              FAQ
            </span>
            <h2 className="text-3xl md:text-4xl font-bold text-slate-900">
              Quick answers
            </h2>
          </div>
          <div className="max-w-2xl mx-auto space-y-3">
            {FAQ.map((item, i) => (
              <button
                key={item.q}
                onClick={() => setOpenFaq(openFaq === i ? null : i)}
                className="w-full text-left bg-white rounded-2xl border border-slate-200 p-5 hover:shadow-md transition"
              >
                <div className="flex items-center justify-between">
                  <span className="font-semibold text-slate-900">
                    {item.q}
                  </span>
                  <span className="text-slate-400 text-xl leading-none">
                    {openFaq === i ? "−" : "+"}
                  </span>
                </div>
                {openFaq === i ? (
                  <p className="text-sm text-slate-600 mt-3 leading-relaxed">
                    {item.a}
                  </p>
                ) : null}
              </button>
            ))}
          </div>
        </div>
      </section>

      {/* BUY (sticky pricing card) */}
      <section id="buy" className="py-20 px-4 bg-slate-900 text-white">
        <div className="container">
          {failedFlag ? (
            <div className="bg-amber-500/15 border border-amber-400/30 rounded-xl p-4 max-w-3xl mx-auto mb-8 text-sm text-amber-200">
              Your last payment didn't complete. You can try again below.
            </div>
          ) : null}

          <div className="grid md:grid-cols-2 gap-8 max-w-4xl mx-auto items-center">
            <div>
              <span className="inline-block px-4 py-1.5 bg-amber-400/15 text-amber-300 text-xs font-semibold rounded-full mb-4">
                Ready when you are
              </span>
              <h2 className="text-3xl md:text-4xl font-bold mb-4 leading-tight">
                One mock test.
                <br />
                <span className="text-amber-300">{idr(price)}.</span>
              </h2>
              <p className="text-slate-300 mb-6">
                Pay once, take it all the way through, get your band score
                and personalised feedback. No subscription, no surprises.
              </p>
              <ul className="space-y-2 text-sm text-slate-300">
                <li className="flex gap-2 items-start">
                  <CheckCircle className="w-4 h-4 text-emerald-400 mt-0.5" />
                  Full 4-skill IELTS test (~2h 45m)
                </li>
                <li className="flex gap-2 items-start">
                  <CheckCircle className="w-4 h-4 text-emerald-400 mt-0.5" />
                  AI-graded against the official IELTS rubric
                </li>
                <li className="flex gap-2 items-start">
                  <CheckCircle className="w-4 h-4 text-emerald-400 mt-0.5" />
                  Branded PDF report emailed to you
                </li>
                <li className="flex gap-2 items-start">
                  <CheckCircle className="w-4 h-4 text-emerald-400 mt-0.5" />
                  Unlimited retakes — pay per attempt
                </li>
              </ul>
            </div>

            <form
              onSubmit={handleBuy}
              className="bg-white text-slate-900 rounded-2xl p-6 shadow-2xl"
            >
              {/* Purchase mode toggle — Mock only vs Bundle. Bundle wins on
                  value (save Rp 78k) but Mock stays as the cheap entry. */}
              <div className="mb-4">
                <label className="block text-xs font-semibold text-slate-700 mb-2 uppercase tracking-wider">
                  Pilih paket
                </label>
                <div className="grid grid-cols-1 gap-2">
                  <button
                    type="button"
                    onClick={() => setPurchaseMode("mock_only")}
                    className={`text-left px-4 py-3 rounded-lg border-2 transition ${
                      purchaseMode === "mock_only"
                        ? "bg-blue-50 border-blue-600"
                        : "bg-white border-slate-200 hover:border-slate-300"
                    }`}
                  >
                    <div className="flex items-center justify-between">
                      <div>
                        <div className="text-sm font-bold text-slate-900">IELTS Mock Test saja</div>
                        <div className="text-[11px] text-slate-500 mt-0.5">1× tes lengkap 4 skill + PDF report</div>
                      </div>
                      <div className="text-base font-bold text-slate-900">{idr(price)}</div>
                    </div>
                  </button>
                  <button
                    type="button"
                    onClick={() => setPurchaseMode("bundle")}
                    className={`text-left px-4 py-3 rounded-lg border-2 transition relative ${
                      purchaseMode === "bundle"
                        ? "bg-amber-50 border-amber-600"
                        : "bg-white border-slate-200 hover:border-slate-300"
                    }`}
                  >
                    <span className="absolute -top-2 right-3 bg-amber-500 text-white text-[10px] font-bold px-2 py-0.5 rounded-full uppercase tracking-wider shadow-sm">
                      Hemat Rp 78rb
                    </span>
                    <div className="flex items-center justify-between">
                      <div className="flex-1">
                        <div className="text-sm font-bold text-slate-900">Bundle Lengkap 🔥</div>
                        <div className="text-[11px] text-slate-600 mt-0.5">
                          Mock Test + AI Tutor 30 hari (unlimited) + 1 Voice Clone gratis
                        </div>
                      </div>
                      <div className="text-right ml-2">
                        <div className="text-[10px] text-slate-400 line-through">
                          {idr(bundleCatalog.data?.standaloneTotalIdr ?? 377000)}
                        </div>
                        <div className="text-base font-bold text-amber-700">
                          {idr(bundleCatalog.data?.priceIdr ?? 299000)}
                        </div>
                      </div>
                    </div>
                  </button>
                </div>
              </div>

              <div className="mb-4">
                <label className="block text-xs font-semibold text-slate-700 mb-2 uppercase tracking-wider">
                  Test type
                </label>
                <div className="grid grid-cols-2 gap-2">
                  <button
                    type="button"
                    onClick={() => setTestType("academic")}
                    className={`px-3 py-2 rounded-lg text-sm font-medium border transition ${
                      testType === "academic"
                        ? "bg-blue-600 text-white border-blue-600"
                        : "bg-white text-slate-700 border-slate-300 hover:border-slate-400"
                    }`}
                  >
                    Academic ({academicCount})
                  </button>
                  <button
                    type="button"
                    onClick={() => setTestType("general")}
                    className={`px-3 py-2 rounded-lg text-sm font-medium border transition ${
                      testType === "general"
                        ? "bg-blue-600 text-white border-blue-600"
                        : "bg-white text-slate-700 border-slate-300 hover:border-slate-400"
                    }`}
                  >
                    General ({generalCount})
                  </button>
                </div>
              </div>

              <Field label="Full name">
                <input
                  type="text"
                  required
                  value={name}
                  onChange={e => setName(e.target.value)}
                  className="w-full px-3 py-2 rounded-lg border border-slate-300 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
              </Field>
              <Field label="Email">
                <input
                  type="email"
                  required
                  value={email}
                  onChange={e => setEmail(e.target.value)}
                  className="w-full px-3 py-2 rounded-lg border border-slate-300 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
              </Field>
              <Field label="WhatsApp number (optional)">
                <input
                  type="tel"
                  value={phone}
                  onChange={e => setPhone(e.target.value)}
                  className="w-full px-3 py-2 rounded-lg border border-slate-300 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
              </Field>

              {error ? (
                <div className="text-xs text-red-700 bg-red-50 border border-red-200 rounded-lg px-3 py-2 mb-3">
                  {error}
                </div>
              ) : null}

              {isFreeNow ? (
                <div className="text-center text-xs text-emerald-700 bg-emerald-50 border border-emerald-200 rounded-lg px-3 py-2 mb-3">
                  🎉 Free during internal beta — no payment required.
                </div>
              ) : null}
              <button
                type="submit"
                disabled={buyDisabled || startBundleCheckout.isPending}
                className={`w-full font-semibold py-3 rounded-lg transition shadow text-white ${
                  purchaseMode === "bundle"
                    ? "bg-gradient-to-r from-amber-500 to-orange-600 hover:from-amber-400 hover:to-orange-500 disabled:from-slate-400 disabled:to-slate-500"
                    : isFreeNow
                    ? "bg-gradient-to-r from-emerald-600 to-teal-700 hover:from-emerald-500 hover:to-teal-600 disabled:from-slate-400 disabled:to-slate-500"
                    : "bg-gradient-to-r from-blue-600 to-indigo-700 hover:from-blue-500 hover:to-indigo-600 disabled:from-slate-400 disabled:to-slate-500"
                }`}
              >
                {(startCheckout.isPending || startBundleCheckout.isPending)
                  ? "Redirecting to checkout…"
                  : purchaseMode === "bundle"
                    ? `🔥 Beli Bundle — ${idr(bundleCatalog.data?.priceIdr ?? 299000)}`
                    : isFreeNow
                      ? "Start free test"
                      : `Beli Mock — ${idr(price)}`}
              </button>

              <p className="text-xs text-slate-500 text-center mt-3">
                No account needed — we'll email your payment link, then your
                test link once you've paid.
              </p>
            </form>
          </div>

          {/* Disclaimer */}
          <div className="text-xs text-slate-400 max-w-3xl mx-auto text-center leading-relaxed mt-12 px-4">
            This is a practice mock test by SpecTa Education. It is not an
            official IELTS score and is not affiliated with British Council,
            IDP, or Cambridge Assessment English. Use it to prepare for the
            real exam.
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
}

function ComparisonCard({
  label,
  value,
  sub,
  tone,
}: {
  label: string;
  value: string;
  sub: string;
  tone: "muted" | "primary" | "accent";
}) {
  const styles = {
    muted: "bg-white border-slate-200 text-slate-900",
    primary: "bg-gradient-to-br from-blue-600 to-indigo-700 border-transparent text-white shadow-lg scale-[1.02]",
    accent: "bg-amber-50 border-amber-200 text-amber-900",
  }[tone];
  return (
    <div className={`rounded-2xl border p-5 ${styles}`}>
      <div className={`text-xs uppercase tracking-wider mb-1 ${
        tone === "primary" ? "text-amber-300" : tone === "accent" ? "text-amber-700" : "text-slate-500"
      }`}>
        {label}
      </div>
      <div className="text-2xl font-bold">{value}</div>
      <div className={`text-xs mt-1 ${
        tone === "primary" ? "text-blue-100" : tone === "accent" ? "text-amber-700" : "text-slate-500"
      }`}>
        {sub}
      </div>
    </div>
  );
}

function Pill({ icon: Icon, text }: { icon: any; text: string }) {
  return (
    <span className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-white text-slate-700 text-xs font-medium rounded-full border border-slate-200 shadow-sm">
      <Icon className="w-3.5 h-3.5 text-blue-600" />
      {text}
    </span>
  );
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="mb-3">
      <label className="block text-xs font-semibold text-slate-700 mb-1 uppercase tracking-wider">
        {label}
      </label>
      {children}
    </div>
  );
}
