/**
 * Terms of Service — required for Google Ads policy compliance on any
 * subscription product. Kept plain and honest: what the user is buying,
 * how billing works, and how they can cancel.
 */
export default function Terms() {
  return (
    <div className="min-h-screen bg-white">
      <div className="max-w-3xl mx-auto px-4 py-12 text-slate-700 leading-relaxed">
        <h1 className="text-3xl font-extrabold text-slate-900 mb-2">Terms of Service</h1>
        <p className="text-sm text-slate-500 mb-8">Last updated: 23 July 2026</p>

        <h2 className="text-xl font-bold text-slate-900 mt-8 mb-2">1. Who we are</h2>
        <p>
          SpecTa Education ("<strong>SpecTa</strong>", "we", "us") is an education consulting
          company based at Jl. Kelapa Nias Raya QE1 No. 14, Kelapa Gading, Jakarta Utara 14240,
          Indonesia. Contact: <a className="text-indigo-600" href="mailto:info@spectaeducation.com">info@spectaeducation.com</a> ·
          WhatsApp <a className="text-indigo-600" href="https://wa.me/62818218388">+62 818 218 388</a>.
        </p>

        <h2 className="text-xl font-bold text-slate-900 mt-8 mb-2">2. What you're buying</h2>
        <p>
          When you subscribe to SpecTa AI IELTS Tutor you get access to AI-graded IELTS Writing
          and Speaking practice, model answers, and practice tracking. Unlimited usage during
          your active billing period.
        </p>

        <h2 className="text-xl font-bold text-slate-900 mt-8 mb-2">3. Free trial</h2>
        <p>
          The free trial gives you one full Writing evaluation and one full Speaking evaluation
          at no cost and requires <strong>no credit card</strong>. After the free evaluations
          you will only be charged if you explicitly choose a paid plan on the pricing page.
        </p>

        <h2 className="text-xl font-bold text-slate-900 mt-8 mb-2">4. Pricing and billing</h2>
        <ul className="list-disc pl-6 space-y-1">
          <li><strong>2-week plan:</strong> Rp 149.000 per 2 weeks, renews every 2 weeks until you cancel.</li>
          <li><strong>Monthly plan:</strong> Rp 249.000 per calendar month, renews monthly until you cancel.</li>
          <li>All prices are in Indonesian Rupiah (IDR) and include applicable taxes.</li>
          <li>Payments are processed via Xendit; we do not store your card details.</li>
        </ul>

        <h2 className="text-xl font-bold text-slate-900 mt-8 mb-2">5. Cancellation</h2>
        <p>
          You can cancel any time from your account dashboard or by emailing
          <a className="text-indigo-600" href="mailto:info@spectaeducation.com"> info@spectaeducation.com</a>.
          Cancellation stops the next renewal — your current period stays active until it ends.
        </p>

        <h2 className="text-xl font-bold text-slate-900 mt-8 mb-2">6. Refunds</h2>
        <p>
          See our <a className="text-indigo-600" href="/refund">Refund Policy</a> for the full
          details. In short: if the product doesn't work as described within the first 7 days of a
          new subscription, contact us and we'll refund you.
        </p>

        <h2 className="text-xl font-bold text-slate-900 mt-8 mb-2">7. Acceptable use</h2>
        <p>
          Don't use the service to submit content generated by SpecTa AI as your own work in a
          real IELTS exam — that's exam fraud and against IELTS rules. Practice only.
        </p>

        <h2 className="text-xl font-bold text-slate-900 mt-8 mb-2">8. Changes</h2>
        <p>
          We may update these terms; the "last updated" date at the top always reflects the
          latest version. Continued use after an update means you accept the new terms.
        </p>

        <h2 className="text-xl font-bold text-slate-900 mt-8 mb-2">9. Governing law</h2>
        <p>These terms are governed by the laws of the Republic of Indonesia.</p>

        <p className="mt-10 text-sm text-slate-500">
          Questions? Email <a className="text-indigo-600" href="mailto:info@spectaeducation.com">info@spectaeducation.com</a>.
        </p>
      </div>
    </div>
  );
}
